// <auto-generated />
using System;
using BattleArena.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleArena.DbManager.Migrations
{
    [DbContext(typeof(BattleArenaDbContext))]
    [Migration("20251124143448_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleArena.Db.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("game_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("game_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("BattleArena.Db.GameRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("PointMultiplier")
                        .HasColumnType("integer")
                        .HasColumnName("point_multiplier");

                    b.Property<int>("QuestionTopicId")
                        .HasColumnType("integer")
                        .HasColumnName("question_topic_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("game_round_status");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionTopicId");

                    b.ToTable("game_rounds");
                });

            modelBuilder.Entity("BattleArena.Db.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<int>("HostId")
                        .HasColumnType("integer")
                        .HasColumnName("host_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_hosts");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationVenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("organization_venues");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationVenueEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationVenueId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_venue_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.HasIndex("OrganizationVenueId");

                    b.ToTable("organization_venue_events");
                });

            modelBuilder.Entity("BattleArena.Db.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("question_answer_type");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("audio_url");

                    b.Property<string>("CorrectAnswerText")
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("correct_answer_text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("image_url");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("question_topic_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("question_type");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("varchar(1032)")
                        .HasColumnName("choice");

                    b.Property<bool>("IsCorrectChoice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct_choice");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_choices");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("QuestionTopicCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("question_topic_category_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTopicCategoryId");

                    b.ToTable("question_topics");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionTopicCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("question_topic_categories");
                });

            modelBuilder.Entity("BattleArena.Db.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("BattleArena.Db.TeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("role");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_players");
                });

            modelBuilder.Entity("BattleArena.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("created_at")
                        .HasColumnOrder(10000);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by")
                        .HasColumnOrder(10001);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time with time zone")
                        .HasColumnName("updated_at")
                        .HasColumnOrder(10002);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by")
                        .HasColumnOrder(10003);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BattleArena.Db.GameRound", b =>
                {
                    b.HasOne("BattleArena.Db.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleArena.Db.QuestionTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("QuestionTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationHost", b =>
                {
                    b.HasOne("BattleArena.Db.User", "Host")
                        .WithMany("OrganizationHosts")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleArena.Db.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationVenue", b =>
                {
                    b.HasOne("BattleArena.Db.Organization", "Organization")
                        .WithMany("Venues")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationVenueEvent", b =>
                {
                    b.HasOne("BattleArena.Db.OrganizationVenue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationVenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("BattleArena.Db.Question", b =>
                {
                    b.HasOne("BattleArena.Db.QuestionTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionChoice", b =>
                {
                    b.HasOne("BattleArena.Db.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionTopic", b =>
                {
                    b.HasOne("BattleArena.Db.QuestionTopicCategory", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("QuestionTopicCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BattleArena.Db.TeamPlayer", b =>
                {
                    b.HasOne("BattleArena.Db.User", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleArena.Db.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BattleArena.Db.User", b =>
                {
                    b.HasOne("BattleArena.Db.Organization", null)
                        .WithMany("Hosts")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("BattleArena.Db.Game", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("BattleArena.Db.Organization", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("BattleArena.Db.OrganizationVenue", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BattleArena.Db.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("BattleArena.Db.QuestionTopicCategory", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BattleArena.Db.Team", b =>
                {
                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("BattleArena.Db.User", b =>
                {
                    b.Navigation("OrganizationHosts");

                    b.Navigation("TeamPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
